PureStake/algosigner

.github/release-drafter.yml, .github/workflows/release-drafter.yml, .github/workflows/zip-release.yml
Add new workflow to build the project and upload the zip to a release after it is created.
=> On new release, test, create zip

packages/extension/src/background/messaging/internalMethods.ts, packages/test-project/tests/basic-ui-e2e.test.js, packages/ui/src/pages/SendAlgos.ts
Errors are now explained better. Updated UI tests to match.
=> Updated error responses on Send Algos

packages/extension/manifest.json, packages/ui/index.html
=> Implemented temp fix for macOS Chrome running on extended screen

packages/test-project/tests/basic-e2e-dapp.test.js, packages/ui/src/components/Account/AssetsList.ts
Added new tests for the test-package, Asset freeze, clawback, destroy. 
Refactored the dapp tests partially for more re-usable components, needs another pass or two. 
Added an ID for the UI asset list elements.
=> Updated dapp tests with Freeze, clawback, destroy. Added id to UI 

packages/extension/src/background/messaging/internalMethods.ts
=> Prevent the addition of already imported accounts

packages/dapp/src/algosigner.ts, packages/extension/src/background/messaging/task.ts, packages/extension/src/background/utils/validator.ts, packages/ui/src/pages/SetPassword.ts
- Missing Formatting on AlgoSigner wrapper
- Fix Console error on Logout
- Fix typo on Validator Error messages
- Add loading spinner to Create Wallet
=> Miscellaneous Fixes

packages/common/src/strings.ts, packages/ui/src/components/DeleteWallet.ts, packages/ui/src/components/LedgerNetworkModify.ts, packages/ui/src/components/LedgerNetworksConfiguration.ts, packages/ui/src/components/SignTransaction/Common/TxTemplate.ts, packages/ui/src/styles.scss
=> Network Config UX improvements

packages/ui/src/components/CreateAccount/ConfirmMnemonic.ts, packages/ui/src/components/CreateAccount/SetAccountName.ts, packages/ui/src/pages/ImportAccount.ts, packages/ui/src/pages/SendAlgos.ts
- Enable the last word selected to be removed
- Fixed bug with words with repeated mnemonics
=> Mnemonic UX Improvements for Account Creation

packages/extension/src/background/messaging/task.ts, packages/extension/src/background/utils/validator.ts, packages/ui/src/pages/SignMultisigTransaction.ts, packages/ui/src/pages/SignTransaction.ts
V1 Signing
> ![image](https://user-images.githubusercontent.com/5742610/127214922-58d2c9b5-bcdf-4ea3-a779-1af0096e1e8a.png)
V2 Signing
> ![image](https://user-images.githubusercontent.com/5742610/127215076-73d8e804-69b2-4381-8da1-2a4e4a0d0766.png)
=> Improve Warnings

packages/extension/package.json, packages/test-project/package.json, packages/ui/package.json
Should fix #267 for v2 Signing
=> Update SDK to v1.11.1

packages/ui/src/components/Account/TransactionsList.ts, packages/ui/src/components/TransactionDetail/TxAppl.ts
=> Display Info for Inner Transactions

README.md, docs/legacy-dApp-integration.md, docs/legacy-signing.md, packages/extension/src/background/messaging/api.ts, packages/extension/src/background/messaging/handler.ts, packages/extension/src/background/messaging/task.ts, packages/extension/src/background/transaction/baseValidatedTxnWrap.ts, packages/extension/src/background/utils/validator.ts, packages/test-project/tests/basic-e2e-dapp.test.js, packages/test-project/tests/dapp-signtxn.test.js
=> Deprecation of incomplete atomic groups && Warning on v1 deprecation

packages/ui/src/components/AccountPreview.ts, packages/ui/src/components/ContactList.ts, packages/ui/src/components/ContactPreview.ts, packages/ui/src/components/CreateAccount/SetAccountName.ts, packages/ui/src/components/LedgerDevice/LedgerHardwareConnector.ts, packages/ui/src/pages/ImportAccount.ts, packages/ui/src/pages/SendAlgos.ts
Here's what it looks like with max length of 32 characters
dApp:
Account name:
Contact Name:
=> Improvements to the Contact Lists

packages/ui/src/pages/Account.ts
=> Add Tooltip with Pending Rewards

packages/ui/src/components/Account/TransactionsList.ts, packages/ui/src/components/ContactList.ts, packages/ui/src/pages/AccountDetails.ts
=> Add Links to GoalSeeker from the Accounts Details page

packages/ui/src/components/Account/AddAssetConfirm.ts, packages/ui/src/pages/Account.ts, packages/ui/src/pages/AddAsset.ts
Changing the nomenclature to reduce confusion for new crypto users.
=> Change UI Opt-in nomenclature

packages/ui/src/components/LedgerDevice/LedgerHardwareSign.ts, packages/ui/src/components/SignTransaction/Common/TxTemplate.ts
=> Fix spacings on Ledger Signing tab

packages/extension/src/background/messaging/task.ts, packages/test-project/tests/dapp-signtxn.test.js
Waiting for confirmation from the Foundation
=> Enable single transaction groups

packages/extension/src/background/messaging/task.ts, packages/test-project/package.json, packages/ui/src/components/SignTransaction/Common/TxAlert.ts, packages/ui/src/index.js, packages/ui/src/pages/Login.ts, packages/ui/src/pages/SignWalletTransaction.ts, packages/ui/src/pages/__snapshots__/Login.test.ts.snap, packages/ui/src/styles.scss
Opens up more space for some of the visually "busier" transactions
Previous:
Updated:
=> Reorganize layout of signing window

packages/common/src/messaging/types.ts, packages/extension/src/background/messaging/internalMethods.ts, packages/extension/src/background/messaging/task.ts, packages/extension/src/background/utils/helper.ts, packages/ui/src/components/SettingsMenu.ts
Improves on the solution meant for #206
=> Improve Cache clearing

packages/common/src/messaging/types.ts, packages/common/src/strings.ts, packages/extension/src/background/messaging/internalMethods.ts, packages/extension/src/background/messaging/task.ts, packages/ui/src/pages/SendAlgos.ts
=> Show Warning when sending funds directly to a Governance accounts

packages/test-project/tests/ui-transactions-e2e.test.js, packages/ui/src/components/MainHeader.ts, packages/ui/src/components/OpenContacts.ts, packages/ui/src/components/SettingsMenu.ts, packages/ui/src/index.js, packages/ui/src/pages/ContactsPage.ts, packages/ui/src/pages/SendAlgos.ts
We've moved the Contacts list out of the Settings menu for easier access and use.
=> Move Contacts list out of Settings Menu

packages/common/src/strings.ts
=> Update 'Governance warning' wording

packages/extension/src/background/messaging/internalMethods.ts, packages/extension/src/background/utils/session.ts, packages/ui/src/components/LedgerDevice/LedgerHardwareSign.ts
Fixes regression caused by #427 ([commit](https://github.com/PureStake/algosigner/commit/243e7a9f5a900a333da57b172749044b837db0d8#diff-b2bebd894437c502c6c60d06fcdb9a339f2913a5385ab81bc497ea211b0b39ae))
Includes some slight changes to the markup to improve readability and clarity, and some additional safety checks.
=> Fix regression affecting Ledger devices

docs/dApp-integration.md, packages/common/src/common.test.ts, packages/common/src/errors.ts, packages/common/src/types.ts, packages/extension/src/background/messaging/handler.ts, packages/extension/src/background/messaging/internalMethods.ts, packages/extension/src/background/messaging/task.ts, packages/test-project/tests/common/helpers.js, packages/test-project/tests/common/tests.js, packages/test-project/tests/dapp-groups.test.js, packages/test-project/tests/dapp-signtxn.test.js
Updated checks, validations and errors based on the [ARC-0001](https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0001.md) standard. Also allows for the use of the new 'stxn' when passing reference txns.
Includes splitting more generic errors into more specific ones to provide better feedback on the problems behind them
=> ARC-0001 Updates

packages/common/src/interfaces/appl.ts, packages/common/src/interfaces/keyreg.ts, packages/extension/package.json, packages/extension/src/background/transaction/actions.test.ts, packages/extension/src/background/transaction/actions.ts, packages/extension/src/background/transaction/applTransaction.ts, packages/extension/src/background/transaction/baseValidatedTxnWrap.ts, packages/extension/src/background/transaction/keyregTransaction.ts, packages/extension/src/background/utils/transactionBuilder.ts, packages/test-project/package.json, packages/ui/package.json, packages/ui/src/components/SignTransaction/Common/TxTemplate.ts, packages/ui/src/components/SignTransaction/TxAppl.ts, packages/ui/src/components/SignTransaction/TxKeyreg.ts, packages/ui/src/styles.scss
Includes some small UI changes to improve the UX of more complex transaction details by making it more noticeable that there's more further content to be scrolled down to:
Before | After
:-------------------------:|:-------------------------:
=> Update to SDK 1.24.1

.github/release-drafter.yml, .github/workflows/cla.yml, packages/common/src/common.test.ts, packages/common/src/errors.ts, packages/common/src/interfaces/keyreg.ts, packages/extension/src/background/messaging/task.ts, packages/extension/src/background/transaction/acfgCreateTransaction.ts, packages/extension/src/background/transaction/acfgTransaction.ts, packages/extension/src/background/transaction/actions.test.ts, packages/extension/src/background/transaction/actions.ts, packages/extension/src/background/transaction/baseValidatedTxnWrap.ts, packages/extension/src/background/transaction/keyregOfflineTransaction.ts, packages/extension/src/background/transaction/keyregOnlineTransaction.ts, packages/extension/src/background/utils/validator.ts, packages/test-project/tests/common/constants.js, packages/test-project/tests/dapp-arcs-signtxns.test.js, packages/test-project/tests/dapp-legacy-signtxn.test.js, packages/test-project/tests/ui-transactions-e2e.test.js, packages/ui/src/components/Account/AssetsList.ts, packages/ui/src/components/CreateAccount/AccountKeys.ts, packages/ui/src/components/SignTransaction/TxAcfg.ts, packages/ui/src/components/SignTransaction/TxAfrz.ts, packages/ui/src/components/SignTransaction/TxAppl.ts, packages/ui/src/components/SignTransaction/TxAxfer.ts, packages/ui/src/components/SignTransaction/TxKeyreg.ts, packages/ui/src/components/SignTransaction/TxPay.ts, packages/ui/src/pages/ImportAccount.ts
Includes improvements to the way information is shown on errors
=> Update validations for Keyreg & Acfg

packages/common/src/config.ts, packages/common/src/types.ts, packages/common/src/types/network.ts, packages/extension/src/background/config.ts, packages/extension/src/background/messaging/internalMethods.test.ts, packages/extension/src/background/messaging/internalMethods.ts, packages/extension/src/background/messaging/task.ts, packages/extension/src/background/transaction/actions.ts, packages/extension/src/background/utils/assetsDetailsHelper.ts, packages/extension/src/background/utils/helper.ts, packages/extension/src/background/utils/networkUrlParser.ts, packages/extension/src/background/utils/session.ts, packages/storage/src/extensionStorage.ts, packages/test-project/tests/dapp-arcs-misc.test.js, packages/test-project/tests/ui-networks-e2e.test.js, packages/ui/src/components/Settings/NetworkConfiguration.ts, packages/ui/src/components/Settings/NetworkModify.ts, packages/ui/src/components/SettingsMenu.ts, packages/ui/src/pages/Enable.ts
- Automatic fetching of genesis info for custom networks without user input, achieving full support for custom networks on `enable()` calls
- Improvements to Network Config UX
- Improved typings and helpers related to networks
- Slightly updated e2e tests
=> Improve Custom Networks
